CRYPTLIB_SOURCES = \
	Cryptlib/Hash/CryptMd5.c \
	Cryptlib/Hash/CryptSha1.c \
	Cryptlib/Hash/CryptSha256.c \
	Cryptlib/Hash/CryptSha512.c \
	Cryptlib/Hash/CryptSm3.c \
	Cryptlib/Pk/CryptAuthenticode.c \
	Cryptlib/Pk/CryptPkcs7Sign.c \
	Cryptlib/Pk/CryptPkcs7VerifyBase.c \
	Cryptlib/Pk/CryptPkcs7VerifyCommon.c \
	Cryptlib/Pk/CryptPkcs7VerifyEku.c \
	Cryptlib/Pk/CryptRsaBasic.c \
	Cryptlib/Pk/CryptRsaExt.c \
	Cryptlib/Pk/CryptTs.c \
	Cryptlib/Pk/CryptX509.c \
	Cryptlib/Rand/CryptRand.c \
	Cryptlib/SysCall/BaseMemAllocation.c \
	Cryptlib/SysCall/BaseStrings.c \
	Cryptlib/SysCall/CrtWrapper.c \
	Cryptlib/SysCall/memset.c \
	Cryptlib/SysCall/TimerWrapper.c \
	Cryptlib/Library/TimerLib.c Cryptlib/Library/Console.c
