# This is a basic workflow that is manually triggered

name: Manual github mirror

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: Mirror from github manually

jobs:
  mirror-main:
    runs-on: ubuntu-20.04
    name: mirror-main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/github-mirror
          fetch-depth: 0
      - name: Mirror main
        id: mirror-main
        run: |
          .github/mirror.sh
