name: mirror

on:
  schedule:
    - cron: '43 4 * * *'

jobs:
  mirror-main:
    runs-on: ubuntu-20.04
    name: mirror-main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/github-mirror
          fetch-depth: 0
      - name: Mirror main
        id: mirror-main
        run: |
          .github/mirror.sh
