name: Build PR patches for CI

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-f31-x64:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:f31
    name: A job to test building on Fedora 31
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do the build
        run: git rebase --exec "make PREFIX=/usr LIBDIR=/usr/lib64 DESTDIR=/destdir EFIDIR=test ENABLE_HTTPBOOT=true ENABLE_SHIM_HASH=true clean all" "${GITHUB_BASE_REF}"
        id: build
      - name: Install in /destdir
        id: install
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: shim
#          path: |
#            /destdir
  pull-request-f32-x64:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:f32
    name: A job to test building on Fedora 32
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do the build
        run: git rebase --exec "make PREFIX=/usr LIBDIR=/usr/lib64 DESTDIR=/destdir EFIDIR=test ENABLE_HTTPBOOT=true ENABLE_SHIM_HASH=true clean all" "${GITHUB_BASE_REF}"
        id: build
      - name: Install in /destdir
        run: make
                  PREFIX=/usr
                  LIBDIR=/usr/lib64
                  DESTDIR=/destdir
                  EFIDIR=test
                  ENABLE_HTTPBOOT=true
                  ENABLE_SHIM_HASH=true
                  install
        id: install
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: shim
#          path: |
#            /destdir
  pull-request-f33-x64:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:f33
    name: A job to test building on Fedora 33
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do the build
        run: git rebase --exec "make PREFIX=/usr LIBDIR=/usr/lib64 DESTDIR=/destdir EFIDIR=test ENABLE_HTTPBOOT=true ENABLE_SHIM_HASH=true clean all" "${GITHUB_BASE_REF}"
        id: build
      - name: Install in /destdir
        run: make
                  PREFIX=/usr
                  LIBDIR=/usr/lib64
                  DESTDIR=/destdir
                  EFIDIR=test
                  ENABLE_HTTPBOOT=true
                  ENABLE_SHIM_HASH=true
                  install
        id: install
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: shim
#          path: |
#            /destdir
  pull-request-f34-x64:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:f34
    name: A job to test building on Fedora 34
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do the build
        run: git rebase --exec "make PREFIX=/usr LIBDIR=/usr/lib64 DESTDIR=/destdir EFIDIR=test ENABLE_HTTPBOOT=true ENABLE_SHIM_HASH=true clean all" "${GITHUB_BASE_REF}"
        id: build
      - name: Install in /destdir
        run: make
                  PREFIX=/usr
                  LIBDIR=/usr/lib64
                  DESTDIR=/destdir
                  EFIDIR=test
                  ENABLE_HTTPBOOT=true
                  ENABLE_SHIM_HASH=true
                  install
        id: install
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: shim
#          path: |
#            /destdir
